package com.example.demo.model.modelEnum;

public enum MaintenanceCatalogType {
    BATTERY_INSPECTION,
    TIRE_ROTATION,
    BRAKE_SYSTEM_CHECK,
    SOFTWARE_UPDATE,
    AIR_FILTER_REPLACEMENT,
    COOLANT_SYSTEM_SERVICE,
    SUSPENSION_INSPECTION,
    WHEEL_ALIGNMENT,
    FULL_VEHICLE_DIAGNOSTIC,
    EMERGENCY_CHARGING_SERVICE
}
